import phrases

ents = {
    'pst': ["yes", "yeah", "exactly", "ok", "yeh", "yep", "correct", "affirmative", "okey", "nice", "right", "ua",
            "perfect", "great", "cool", "accept", "microwavable", "precisely", "available", "acceptable", "drivable"],

    'pst_1': ["you are right", "just so", "still available", "yes, it is", "ok thats great", "perfect, thanks",
            "whats offer", "thank you for contact me", "cool", "why not", "if its free", "accept", "whats the offer",
            "thanks for the offer", "you may well say so", "go ahead", "i am interested", "with my", "its my",
              "im interested"],

    'ngt': ["sold", "no", "didnt" "not", "nope", "dont", "salt"],

    'ngt_1': ["its sold", "no way", "sorry, sold", "its gone", "it sold"
            "sold it", "i dont have a car for sale", "you have missed it",
            "no thanks", "not for me", "i dont think so", "fuck off", "piss off", "thats not my",
            "i dont own", "thats not correct", "thats not", "is wrong", "i live in", "where did you get",
            "why do you need to know that?", "my mobile is", "dont know", "what is service history",
            "i have lost", "not interested", "changed my mind"]
}

subjects_of_stages = ['my greeting', 'registration number of your car', ' mileage of your car',
                      'the nearest city to you', 'phone number to offer', 'your car service history',
                      'making you offer']

repeat_subj = [' is your car available?', 'are you interested?', 'registration number of your car?', '',
               'the nearest city to you.', phrases.fivth_stage, phrases.sixth_stage]

serv_hist = ['1', '2', '3', 'full', 'part', 'parts', 'missing', 'lost', 'miss', 'no', 'one', 'two', 'three', 'tree',
             'haven\'t', 'to', 'nissan', 'meeting']

serv_hist_kind = {'1': 'Full service history', 'full': 'Full service history', 'one': 'Full service history',
                  '2': 'Part service history', 'part': 'Part service history', 'parts': 'Part service history',
                  'two': 'Part service history', 'to': 'Part service history',
                  '3': 'haven\'t service history', 'no': 'haven\'t service history', 'tree': 'haven\'t service history',
                  'miss': 'haven\'t service history', 'lost': 'haven\'t service history',
                  'missing': 'haven\'t service history', 'haven\'t': 'haven\'t service history',
                  'three': 'haven\'t service history', 'nissan': 'haven\'t service history',
                  'meeting': 'haven\'t service history'}

cities = ['London', 'Birmingham', 'Leeds', 'Glasgow', 'Sheffield', 'Bradford', 'Liverpool', 'Edinburgh', 'Manchester',
          'Bristol', 'Kirklees', 'Fife', 'Wirral', 'North Lanarkshire', 'Wakefield', 'Cardiff', 'Dudley', 'Wigan',
          'East Riding', 'South Lanarkshire', 'Coventry', 'Belfast', 'Leicester', 'Sunderland', 'Sandwell', 'Doncaster',
          'Stockport', 'Sefton', 'Nottingham', 'Newcastle upon Tyne', 'Kingston upon Hull', 'Bolton', 'Walsall', 'Arun',
          'Plymouth', 'Rotherham', 'Stoke on Trent', 'Wolverhampton', 'Rhondda', 'Cynon', 'Oldham', 'Derby',
          'South Gloucestershire', 'Swansea', 'Salford', 'Aberdeenshire', 'Barnsley', 'Tameside', 'Trafford', 'York',
          'Aberdeen', 'Southampton', 'Highland', 'Rochdale', 'Solihull', 'Gateshead', 'Milton Keynes', 'North Tyneside',
          'Calderdale', 'Northampton', 'Portsmouth', 'Warrington', 'North Somerset', 'Luton', 'Suffolk Coastal',
          'Stockton on Tees', 'Renfrewshire', 'Thamesdown', 'Southend on Sea', 'New Forest', 'Caerphilly', 'Wycombe',
          'Carmarthenshire', 'Bath and North East Somerset', 'Basildon', 'Bournemouth', 'Peterborough', 'Colchester',
          'North East Lincolnshire', 'Chelmsford', 'Brighton', 'South Tyneside', 'Charnwood', 'Aylesbury Vale', 'Swale',
          'Knowsley', 'North Lincolnshire', 'Huntingdonshire', 'Macclesfield', 'Blackpool', 'West Lothian', 'Newbury',
          'South Somerset', 'Dundee', 'Basingstoke and Deane', 'Harrogate', 'Dumfries and Galloway', 'Middlesbrough',
          'Flintshire', 'Rochester upon Medway', 'The Wrekin', 'Falkirk', 'Reading', 'Wokingham', 'North Ayrshire',
          'Windsor and Maidenhead', 'Maidstone', 'Redcar and Cleveland', 'Blackburn', 'Neath Port Talbot', 'Poole',
          'Wealden', 'Lancaster', 'Newport', 'Canterbury', 'Preston', 'Dacorum', 'Cherwell', 'Mid Sussex',
          'Perth and Kinross', 'Thurrock', 'Tendring', 'Kings Lynn and West Norfolk', 'St Albans', 'Bridgend', 'Halton',
          'Elmbridge', 'South Cambridgeshire', 'Braintree', 'Norwich', 'Thanet', 'Isle of Wight', 'South Oxfordshire',
          'Guildford', 'Stafford', 'Powys', 'East Hertfordshire', 'Torbay', 'Wrexham Maelor', 'East Devon', 'Horsham',
          'East Lindsey', 'Warwick', 'East Ayrshire', 'Newcastle under Lyme', 'North Wiltshire', 'South Kesteven',
          'Epping Forest', 'Vale of Glamorgan', 'Reigate and Banstead', 'Mid Bedfordshire',  'St Helens', 'Bassetlaw',
          'Nuneaton and Bedworth', 'Gwynedd', 'Havant and Waterloo', 'Teignbridge', 'Cambridge', 'Vale Royal', 'Oxford',
          'Amber Valley', 'North Hertfordshire', 'South Ayrshire', 'Waverley', 'Broadland', 'Crewe and Nantwich',
          'Breckland', 'Ipswich', 'Pembrokeshire', 'Vale of White Horse', 'Salisbury', 'Gedling', 'Eastleigh', 'Conway',
          'Broxtowe', 'Stratford on Avon', 'South Bedfordshire', 'Angus', 'East Hampshire', 'East Dunbartonshire',
          'Sevenoaks', 'Slough', 'Bracknell Forest', 'West Lancashire', 'West Wiltshire', 'Ashfield', 'Lisburn', 'Taff',
          'Scarborough', 'Stroud', 'Wychavon', 'Waveney', 'Exeter', 'Dover', 'Test Valley', 'Gloucester', 'Erewash',
          'Cheltenham', 'Scottish Borders', 'Bury', 'Bedford']


part_of_cities = {'West Lancashire': 'Lancashire', 'Bracknell Forest': 'Bracknell', 'East Hampshire': 'Hampshire',
                  'East Dunbartonshire': 'Dunbartonshire', 'Kingston upon Hull': 'Kingston', 'East Riding': 'Riding',
                  'Stratford on Avon': 'Stratford', 'Crewe and Nantwich': 'Crewe', 'crewe and Nantwich': 'Nantwich',
                  'Amber Valley': 'Amber', 'Havant and Waterloo': 'Havant', 'Nuneaton and Bedworth': 'Nuneaton',
                  'nuneaton and Bedworth': 'Bedworth', 'Suffolk Coastal': 'Suffolk', 'reigate and Banstead': 'Banstead',
                  'Reigate and Banstead': 'Reigate', 'Vale of Glamorgan': 'Glamorgan', 'South Kesteven': 'Kesteven',
                  'Newcastle upon Tyne': 'Newcastle', 'Wrexham Maelor': 'Wrexham', 'wrexham Maelor': 'Maelor',
                  'East Devon': 'Devon', 'East Lindsey': 'Lindsey', 'Dumfries and Galloway': 'Galloway',
                  'Isle of Wight': 'Wight', 'South Cambridgeshire': 'Cambridgeshire', 'St Albans': 'Albans',
                  'Kings Lynn and West Norfolk': 'Lynn', 'Kings Lynn & West Norfolk': 'Norfolk', 'Mid Sussex': 'Sussex',
                  'Perth and Kinross': 'Perth', 'Perth & Kinross': 'Kinross', 'Windsor and Maidenhead': 'Windsor',
                  'Redcar and Cleveland': 'Redcar', 'Redcar & Cleveland': 'Cleveland', 'Neath Port Talbot': 'Talbot',
                  'The Wrekin': 'Wrekin', 'Rochester upon Medway': 'Rochester', 'Rochester up. Medway': 'Medway',
                  'Dumfries & Galloway': 'Dumfries', 'Basingstoke and Deane': 'Basingstoke', 'St Helens': 'Helens',
                  'Basingstoke & Deane': 'Deane', 'West Lothian': 'Lothian', 'Aylesbury Vale': 'Aylesbury',
                  'Southend on Sea': 'Southend', 'Stockton on Tees': 'Stockton', 'Milton Keynes': 'Milton',
                  'milton keynes': 'Keynes', 'South Gloucestershire': 'Gloucestershire', 'Stoke on Trent': 'Stoke',
                  'Windsor & Maidenhead': 'Maidenhead', 'South Oxfordshire': 'Oxfordshire', 'Stoke o Trent': 'Trent',
                  'Chester': 'Chester'}

scotish_city = ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee', 'Paisley', 'East Kilbride', 'Inverness', 'Livingston',
                'Hamilton', 'Cumbernauld', 'Dunfermline', 'Kirkcaldy', 'Ayr', 'Perth', 'Kilmarnock', 'Coatbridge',
                'Greenock', 'Glenrothes', 'Airdrie', 'Stirling', 'Falkirk', 'Irvine', 'Dumfries', 'Motherwell',
                'Rutherglen', 'Wishaw', 'Cambuslang', 'Bearsden', 'Clydebank', 'Newton Mearns', 'Arbroath',
                'Musselburgh', 'Bishopbriggs', 'Elgin', 'Renfrew', 'Bathgate', 'Bellshill', 'Alloa', 'Dumbarton',
                'Kirkintilloch', 'Peterhead', 'Barrhead', 'Grangemouth', 'Blantyre', 'St Andrews', 'Kilwinning',
                'Johnstone', 'Bonnyrigg', 'Penicuik', 'Viewpark', 'Erskine', 'Broxburn', 'Port Glasgow', 'Larkhall']

welsh_city = ['Cardiff', 'Swansea', 'Newport', 'Wrexham', 'Merthyr Tydfil', 'Barry', 'Neath', 'Cwmbran', 'Bridgend',
              'Llanelli', 'Caerphilly', 'Port Talbot', 'Pontypridd', 'Aberdare', 'Colwyn Bay', 'Pontypool', 'Penarth',
              'Rhyl', 'Blackwood', 'Buckley', 'Ystrad Mynach', 'Maesteg', 'Ebbw Vale', 'Aberystwyth', 'Bangor',
              'Tonypandy', 'Gelligaer', 'Prestatyn', 'Shotton', "Connah's Quay", 'Carmarthen', 'Gorseinon', 'Porthcawl',
              'Llandudno', 'Risca', 'Flint', 'Tredegar', 'Porth', 'Haverfordwest', 'Church Village', 'Pyle',
              'Milford Haven', 'Rhosllannerchrugog', 'Abergavenny', 'Rhondda', 'Llantrisant', 'Chepstow', 'Pontardawe',
              'Bargoed', 'Holyhead', 'Newtown', 'Mountain Ash', 'Caldicot', 'Abertillery', 'Sarn', 'Llandudno',
              'Abergele', 'Ystradgynlais/Ystalyfera', 'Monmouth', 'Mold', 'Holywell', 'Pembroke Dock', 'Newbridge',
              'Kinmel Bay', 'Caernarfon', 'Tonyrefail', 'Pontllanfraith', 'Pencoed', 'Pontarddulais', 'Caerleon',
              'Denbigh', 'Bedwas', 'Brecon', 'Llantwit Major', 'Beddau', 'Ammanford', 'Treharris', 'Treorchy',
              'Pembroke', 'Dinas Powys', 'Ferndale', 'Cefn-mawr', 'Sandycroft', 'Llanharan', 'Abertridwr', 'Senghenydd',
              'Rhoose', 'Burry Port', 'Abercynon', 'Welshpool', 'Briton Ferry', 'Magor', 'Crumlin', 'Malltraeth',
              'Coedpoeth', 'Penygroes', 'Blaenavon', "Taff's Well", 'RAF Station St Athan', 'Brynmawr', 'Ruthin',
              'Aberavon', 'Treherbert', 'Ewloe', 'Cwmafan', 'Abercarn', 'Llandrindod Wells', 'Rhymney', 'Saltney',
              'Gresford', 'Menai Bridge', 'Llangefni', 'Blaina', 'Tenby', 'Llay', 'Nelson', 'Nantyglo', 'Penrhyn Bay',
              'Glanaman', 'Llangennech', 'Tumble', 'Pontycymer', 'Hope/Caergwrle', 'Glyn-Neath', 'New Tredegar',
              'Cardigan', 'Bagillt', 'Pwllheli', 'Glyncoch', 'Chirk', 'Conwy', 'Cowbridge', 'Bethesda', 'Tycroes',
              'Llanbradach', 'Rhuddlan', 'Neyland', 'Blaenau Ffestiniog', 'Tylorstown', 'Llanfairfechan', 'Penyffordd',
              'Aberfan', 'Ynysybwl', 'Bishopston', 'Llangollen', 'Fishguard', 'Ruabon', 'St Asaph', 'Llanrwst',
              'Amlwch', 'Penparcau', 'Ogmore Vale', 'Llanfairpwll', 'Tywyn', 'Gwaun-Cae-Gurwen', 'Llanharry',
              'Knighton', 'Llanhilleth', 'Porthmadog', 'Lampeter', 'Llanidloes', 'Usk', 'Builth Wells', 'Llandybie',
              'Crickhowell', 'Kidwelly', 'Saundersfoot', 'Rhostyllen', 'Cwm', 'Dolgellau', 'Brynaman', 'Penmaenmawr',
              'Hendreforgan', 'Creigiau', 'Machen', 'Valley', 'Nant-y-Moel', 'Corwen', 'Marshfield', 'Barmouth',
              'Pentyrch', 'Y Felinheli', 'Leeswood', 'Dyserth', 'Narberth', 'Gilwern', 'Benllech', 'Machynlleth',
              'Pembrey', 'Seven Sisters', 'Queensferry', 'Resolven', 'Llandovery', 'Presteigne', 'Rossett', 'Southgate',
              'St Clears', 'Bala', 'Johnston', 'Penclawdd', 'Pontlottyn', 'Gilfach Goch', 'Llanrug', 'Newcastle Emlyn',
              'Llanberis', 'Rhayader', 'Rogiet', 'Llanfair Caereinion', 'Llandeilo', 'Bodelwyddan', 'Penygroes',
              'Whitland', 'Criccieth', 'Glan Conwy', 'Goodwick', 'Soughton', 'Pontyberem', 'Pontlliw', 'Talgarth',
              'Llanybydder', 'Mostyn', 'Crynant', 'Trimsaran', 'Bow Street', 'Croeserw', 'Penrhyndeudraeth',
              'Trearddur Bay', 'Northop Hall', 'Cilgerran', 'Llangynwyd/Pont-rhyd-y-cyff', 'Llanfyllin', 'Hay-on-Wye',
              'Abertysswg', 'Trevor', 'Harlech', 'Llandysul', 'Aberaeron', 'St Davids', 'Cwmllynfell', 'Pwll',
              'Fernhill', 'Deiniolen', 'Nefyn', 'Beaumaris', 'Dwygyfylchi', 'Whelston', 'Penrhyn-coch', 'Caerwys',
              'Afonwen', 'Tregarth', 'Llanddulas', 'Efail Isaf', 'Montgomery', 'Aberporth', 'Llanfoist', 'New Quay',
              'Waunfawr', 'Cemaes', 'Tregaron', 'Bethel', 'Gaerwen', 'Brynsadler', 'Blaengwrach', 'Llanerchymedd',
              'Penybanc', 'St Dogmaels', 'Holt', 'Talysarn', 'Mynydd Marian', 'Bodedern', 'Rhosneigr', 'Aberbargoed',
              'Bontnewydd', 'Rachub', 'Gwernaffield', 'Newborough', 'Groeslon', 'Llan Ffestiniog', 'Morfa Nefyn',
              'Llangoed', 'Pontrhydyfen', 'Pantymwyn', 'Laugharne', 'Trefor', 'Abersoch', 'Llanfihangel-yn-Nhowyn',
              'Castleton', 'Aberdyfi', 'Gwalchmai', 'Fairbourne', 'Rhosybol', 'Moelfre', 'Llanddona', 'Rhostryfan',
              'Pwll Trap', 'Llanbadarn Fawr', 'Chwilog', 'Trawsfynydd', 'Templeton', 'Llanbedrog', 'Trefriw', 'Dwyran',
              'Llanwrtyd Wells', 'Penysarn', 'New Hedges', 'Llanfechell', 'Pentraeth', 'Cymmer', 'Mynytho', 'Llysfaen',
              'Llwyngwril', 'Bryn Pydew', 'Dolgarrog', 'Sydall', 'Parcllyn', 'Bryngwran', 'Pentre Berw', 'Llanbedr',
              'Llangristiolus', 'Caergeiliog', 'Betws-yn-Rhos', 'Cerrigydrudion', 'Pulford', 'Betws-y-Coed']

full_city_lst = ['Appleby-in-Westmorland', 'South Woodham Ferrers', 'Ashton-in-Makerfield', 'Kingston upon Thames',
          'Newbiggin-by-the-Sea', 'Newcastle-under-Lyme', 'Richmond-upon-Thames', 'Newcastle upon Tyne',
          'Saltburn-by-the-Sea', 'Stourport-on-Severn', 'Stratford-upon-Avon', 'Barton-upon-Humber',
          'Berwick-upon-Tweed', "Bishop's Stortford", 'Budleigh Salterton', 'Houghton-le-Spring', 'Kingston-upon-Hull',
          'Princes Risborough', 'Sutton-in-Ashfield', 'Walton-on-the-Naze', 'Wells-next-the-Sea', 'Welwyn Garden City',
          'Ashby-de-la-Zouch', 'Ashton-under-Lyne', 'Barrow-in-Furness', 'Burnham-on-Crouch', 'Burton-upon-Trent',
          'Chester-le-Street', 'Grange-over-Sands', 'Market Harborough', 'Marston Moretaine', 'Newton-le-Willows',
          'Shipston-on-Stour', 'Upton-upon-Severn', 'Weston-super-Mare', 'Wotton-under-Edge', "Bishop's Waltham",
          'Bradford-on-Avon', 'Chipping Campden', 'Chipping Sodbury', 'Great Torrington', 'Henley-on-Thames',
          'Leighton Buzzard', 'Lytchett Minster', 'Moretonhampstead', 'Moreton-in-Marsh', 'Poulton-le-Fylde',
          'Stockton-on-Tees', 'Stow-on-the-Wold', 'Sutton Coldfield', 'Walton-on-Thames', 'Wath-upon-Dearne',
          'Wimborne Minster', 'Bishop Auckland', "Bishop's Castle", 'Blandford Forum', 'Bury St Edmunds',
          'Chipping Norton', 'Church Stretton', 'Fenny Stratford', 'Hemel Hempstead', 'Henley-in-Arden',
          'Irthlingborough', 'Kirkby Lonsdale', 'Lytham St Annes', 'Market Weighton', 'Midsomer Norton',
          'Newark-on-Trent', 'Newport Pagnell', 'Newton Aycliffe', 'Norton Radstock', 'Quintrell Downs',
          'St Columb Major', 'Shoreham-by-Sea', 'Southend-on-Sea', 'Stony Stratford', 'Tunbridge Wells',
          'Wootton Bassett', 'Barnard Castle', 'Barton-le-Clay', 'Bexhill-on-Sea', 'Burnham-on-Sea', 'Burton Latimer',
          'Chipping Ongar', 'Clacton-on-Sea', 'Downham Market', 'East Grinstead', 'Ellesmere Port', 'Frinton-on-Sea',
          'Great Yarmouth', 'Haywards Heath', 'Hetton-le-Hole', 'Higham Ferrers', 'Leamington Spa', 'Market Deeping',
          'Market Drayton', 'Melton Mowbray', 'Needham Market', 'Ottery St Mary', 'Saffron Walden', 'Cambridgeshire',
          'Sawbridgeworth', 'Shepton Mallet', 'Stoke-on-Trent', 'Wellingborough', 'Bradley Stoke', 'Brierley Hill',
          'Brightlingsea', 'Buckfastleigh', 'Droitwich Spa', 'Fordingbridge', 'Godmanchester', 'Hebden Bridge',
          'Hove Hucknall', 'Kidderminster', 'Knaresborough', 'Littlehampton', 'Middlesbrough', 'Northallerton',
          'North Walsham', 'Rickmansworth', 'Sittingbourne', 'South Shields', 'Tenbury Wells', 'Waltham Abbey',
          'Waltham Cross', 'West Bromwich', 'Whaley Bridge', 'Wolverhampton', 'Attleborough', 'Barnoldswick',
          'Beaconsfield', 'Bognor Regis', 'Burgess Hill', 'Chesterfield', 'Christchurch', 'Featherstone',
          'Gainsborough', 'Great Dunmow', 'High Wycombe', 'Huddersfield', 'Killingworth', 'Loughborough',
          'Macclesfield', 'Market Rasen', 'Much Wenlock', 'Newton Abbot', 'Paddock Wood', 'Peterborough',
          'Queenborough', 'Rowley Regis', 'Skelmersdale', 'Southborough', 'South Molton', 'Stocksbridge',
          'Westhoughton', 'Westward Ho!', 'Barnt Green', 'Basingstoke', 'Berkhamsted', 'Biggleswade', 'Borehamwood',
          'Bournemouth', 'Bridlington', 'Broadstairs', 'Buntingford', 'Castle Cary', 'Cirencester', 'Cleckheaton',
          'Cleethorpes', 'Cockermouth', 'Conisbrough', 'Cramlington', 'Crowborough', 'connor town', 'Darley Dale',
          'Farnborough', 'Framlingham', 'Glastonbury', 'Guisborough', 'Haltwhistle', 'Kingsbridge', "King's Lynn",
          'Knottingley', 'Leatherhead', 'Lostwithiel', 'Lutterworth', 'Mablethorpe', 'Manningtree', 'Marlborough',
          'Northampton', 'Petersfield', 'Pocklington', 'Potters Bar', 'Ross-on-Wye', 'Scarborough', 'Shaftesbury',
          'Southampton', 'Stalybridge', 'Stourbridge', 'Swadlincote', 'Wallingford', 'Walthamstow', 'West Mersea',
          'Westminster', 'Whitley Bay', 'Accrington', 'Altrincham', 'Atherstone', 'Barnstaple', 'Beaminster',
          'Bedlington', 'Billericay', 'Birmingham', 'Bollington', 'Bottesford', 'Bridgnorth', 'Bridgwater',
          'Bromsgrove', 'Brownhills', 'Buckingham', 'Canterbury', 'Castleford', 'Chadderton', 'Chelmsford',
          'Cheltenham', 'Chichester', 'Chippenham', 'Cinderford', 'Coggeshall', 'Colchester', 'Crowthorne',
          'Cullompton', 'Darlington', 'Desborough', 'Dinnington', 'Dorchester', 'Dukinfield', 'Easingwold',
          'Eastbourne', 'Edenbridge', 'Failsworth', 'Felixstowe', 'Folkestone', 'Gillingham', 'Gillingham',
          'Gloucester', 'Halesworth', 'Hartlepool', 'Heathfield', 'Holsworthy', 'Horncastle', 'Hungerford',
          'Hunstanton', 'Huntingdon', 'Ilfracombe', 'Kenilworth', 'Launceston', 'Leominster', 'Letchworth',
          'Long Eaton', 'Lyme Regis', 'Maidenhead', 'Malmesbury', 'Manchester', 'Mexborough', 'Middlewich',
          'Nailsworth', 'New Milton', 'Shropshire', 'New Romney', 'Nottingham', 'Okehampton', 'Peacehaven',
          'Pontefract', 'Portishead', 'Portsmouth', 'St Austell', 'Saxmundham', 'Scunthorpe', 'Sedgefield',
          'Sheringham', 'Shrewsbury', 'Spennymoor', 'Stainforth', 'Stapleford', 'Stowmarket', 'Sunderland',
          'Teignmouth', 'Tewkesbury', 'Trowbridge', 'Twickenham', 'Wadebridge', 'Wandsworth', 'Warminster',
          'Washington', 'Wednesbury', 'Wellington', 'West Kirby', 'Whitchurch', 'Whitehaven', 'Whitstable',
          'Willenhall', 'Winchcombe', 'Winchelsea', 'Winchester', 'Windermere', 'Withernsea', 'Woodbridge',
          'Workington', 'Adlington', 'Aldeburgh', 'Aldershot', 'Ashbourne', 'Ashburton', 'Ashington', 'Axminster',
          'Aylesbury', 'Bebington', 'Blackburn', 'Blackpool', 'Bletchley', 'Bracknell', 'Bradninch', 'Braintree',
          'Brentford', 'Brentwood', 'Brighouse', 'Burntwood', 'Blackburn', 'Camberley', 'Cambridge', 'Camelford',
          'Carnforth', 'Carterton', 'Charlbury', 'Chatteris', 'Cleveleys', 'Clitheroe', 'Coalville', 'Congleton',
          'Corbridge', 'Cranfield', 'Crewkerne', 'Cuckfield', 'Dartmouth', 'Doncaster', 'Driffield', 'Dronfield',
          'Droylsden', 'Dunstable', 'Eastleigh', 'Ellesmere', 'Faringdon', 'Farnworth', 'Faversham', 'Ferryhill',
          'Fleetwood', 'Gateshead', 'Godalming', 'Gravesend', 'Guildford', 'Harpenden', 'Harrogate', 'Haslemere',
          'Haverhill', 'Hemsworth', 'Herne Bay', 'Highworth', 'Hoddesdon', 'Holmfirth', 'Hugh Town', 'Ilchester',
          'Ilminster', 'Ivybridge', 'Kettering', 'Kidsgrove', 'Kimberley', 'Knutsford', 'Lancaster', 'Leicester',
          'Lichfield', 'Liverpool', 'Longridge', 'Lowestoft', 'Lymington', 'Lofthouse', 'Maidstone', 'Mansfield',
          'Middleham', 'Middleton', 'Morecambe', 'Newmarket', 'New Mills', 'Normanton', 'Northwich', 'Orpington',
          'Painswick', 'Penistone', 'Pickering', 'Poltimore', 'Portslade', 'Rochester', 'Rotherham', 'St Albans',
          'St Blazey', 'St Helens', 'Salisbury', 'Sandhurst', 'Sevenoaks', 'Sheerness', 'Sheffield', 'Sherborne',
          'Smethwick', 'Southport', 'Southwell', 'Southwold', 'Stevenage', 'Stockport', 'Stotfield', 'Streatham',
          'Tadcaster', 'Tavistock', 'Tenterden', 'Thornbury', 'Todmorden', 'Tonbridge', 'Tottenham', 'Towcester',
          'Ulverston', 'Uppingham', 'Uttoxeter', 'Wakefield', 'Westerham', 'Weybridge', 'Whitworth', 'Wimbledon',
          'Wincanton', 'Wokingham', 'Woodstock', 'Worcester', 'Wymondham', 'Abingdon', 'Alcester', 'Aldridge',
          'Alfreton', 'Amersham', 'Amesbury', 'Ampthill', 'Aspatria', 'Axbridge', 'Bakewell', 'Barnsley', 'Basildon',
          'Bedworth', 'Beverley', 'Bicester', 'Biddulph', 'Bideford', 'Bolsover', 'Brackley', 'Bradford', 'Bridport',
          'Brighton', 'Bromyard', 'Camborne', 'Carlisle', 'Chagford', 'Cheshunt', 'Clevedon', 'Coleford', 'Cotgrave',
          'Coventry', 'Crayford', 'Crediton', 'Dagenham', 'Dartford', 'Daventry', 'Dewsbury', 'East Ham', 'Eastwood',
          'Fairford', 'Fakenham', 'Falmouth', 'Ferndown', 'Flitwick', 'Fordwich', 'Frodsham', 'Grantham', 'Hadleigh',
          'Hailsham', 'Halewood', 'Halstead', 'Hastings', 'Hatfield', 'Hereford', 'Hertford', 'Hinckley', 'Hounslow',
          'Ilkeston', 'Keighley', 'Kempston', 'Kesgrave', 'Keynsham', 'Lechlade', 'Lewisham', 'Liskeard', 'Loughton',
          'Maryport', 'Melksham', 'Midhurst', 'Minehead', 'Nantwich', 'Newhaven', 'Nuneaton', 'Ollerton', 'Ormskirk',
          'Oswestry', 'Paignton', 'Penzance', 'Pershore', 'Peterlee', 'Petworth', 'Plymouth', 'Polegate', 'Portland',
          'Ramsgate', 'Rayleigh', 'Redditch', 'Richmond', 'Ringwood', 'Rochdale', 'Rochford', 'Rothbury', 'Rothwell',
          'St Asaph', 'Cornwall', 'St Neots', 'Salcombe', 'Sandbach', 'Sandwich', 'Shanklin', 'Shepshed', 'Sidmouth',
          'Skegness', 'Sleaford', 'Snodland', 'Solihull', 'Somerton', 'Southall', 'Southsea', 'Spalding', 'Stafford',
          'Stamford', 'Staunton', 'Staveley', 'Swaffham', 'Tamworth', 'Thatcham', 'Thetford', 'Thornaby', 'Tickhill',
          'Tiverton', 'Torpoint', 'Uckfield', 'Uxbridge', 'Wadhurst', 'Wallasey', 'Wendover', 'Westbury', 'West Ham',
          'Wetherby', 'Weymouth', 'Whitnash', 'Wickford', 'Winsford', 'Wivenhoe', 'Wombwell', 'Woolwich', 'Worthing',
          'Yarmouth', 'Alnwick', 'Alsager', 'Andover', 'Arundel', 'Ashford', 'Aylsham', 'Baldock', 'Banbury', 'Barking',
          'Beccles', 'Bedford', 'Beeston', 'Bentham', 'Bewdley', 'Bilston', 'Bingham', 'Bristol', 'Brixham', 'Bromley',
          'Burford', 'Burnley', 'Caistor', 'Cannock', 'Chatham', 'Chesham', 'Chester', 'Chorley', 'Crawley', 'Croydon',
          'Dawlish', 'Dereham', 'Devizes', 'Dorking', 'Dursley', 'Enfield', 'Epworth', 'Evesham', 'Exmouth', 'Fareham',
          'Farnham', 'Glossop', 'Gosport', 'Grimsby', 'Hackney', 'Halifax', 'Harwich', 'Helston', 'Heswall', 'Heywood',
          'Hitchin', 'Honiton', 'Hornsea', 'Horsham', 'Horwich', 'Hoylake', 'Ipswich', 'Keswick', 'Kington', 'Kirkham',
          'Ledbury', 'Leiston', 'Leyland', 'Lincoln', 'Maghull', 'Malvern', 'Margate', 'Matlock', 'Morpeth', 'Nailsea',
          'Newbury', 'Newport', 'Newport', 'Newquay', 'Northam', 'Norwich', 'Oldbury', 'Outwood', 'Padstow', 'Penrith',
          'Prescot', 'Preston', 'Prudhoe', 'Reading', 'Redhill', 'Redruth', 'Reigate', 'Retford', 'Romford', 'Royston',
          'Rugeley', 'Runcorn', 'Rushden', 'Rutland', 'St Ives', 'St Ives', 'Salford', 'Saltash', 'Sandown', 'Seaford',
          'Shildon', 'Skipton', 'Southam', 'Spilsby', 'Staines', 'Stanley', 'Sudbury', 'Swanage', 'Swanley', 'Swindon',
          'Swinton', 'Taunton', 'Telford', 'Tetbury', 'Thaxted', 'Tilbury', 'Torquay', 'Ventnor', 'Verwood', 'Walsall',
          'Wantage', 'Wareham', 'Warwick', 'Watchet', 'Watford', 'Whiston', 'Wigston', 'Winslow', 'Wisbech', 'Worksop',
          'Yateley', 'Alford', 'Alston', 'Askern', 'Barnet', 'Batley', 'Battle', 'Bawtry', 'Bedale', 'Belper', 'Bodmin',
          'Bolton', 'Boston', 'Bourne', 'Bungay', 'Buxton', 'Cromer', 'Crowle', 'Darwen', 'Denton', 'Didcot', 'Dudley',
          'Durham', 'Ealing', 'Earley', 'Epping', 'Exeter', 'Filton', 'Foxley', 'Harlow', 'Harrow', 'Havant', 'Hawley',
          'Heanor', 'Hendon', 'Hessle', 'Hexham', 'Horley', 'Ilford', 'Ilkley', 'Jarrow', 'Kendal', 'Kirkby', 'Leyton',
          'Lizard', 'London', 'Ludlow', 'Lydney', 'Lynton', 'Maldon', 'Maltby', 'Malton', 'Marlow', 'Morley', 'Neston',
          'Newent', 'Oakham', 'Oldham', 'Ossett', 'Oundle', 'Oxford', 'Penryn', 'Potton', 'Pudsey', 'Raunds', 'Redcar',
          'Ripley', 'Romsey', 'Seaton', 'Selsey', 'Settle', 'Shiraz', 'Sidcup', 'Slough', 'Street', 'Strood', 'Stroud',
          'Sutton', 'Tadley', 'Thirsk', 'Thorne', 'Tipton', 'Totnes', 'Totton', 'Walmer', 'Watton', 'Whitby', 'Widnes',
          'Witham', 'Witney', 'Woburn', 'Woking', 'Wooler', 'Yeadon', 'Yeovil', 'Yoxall', 'Acton', 'Alton', 'Amble',
          'Bacup', 'Blyth', 'Brigg', 'Calne', 'Chard', 'Colne', 'Corby', 'Cowes', 'Crewe', 'Derby', 'Dover', 'Egham',
          'Epsom', 'Erith', 'Esher', 'Filey', 'Fleet', 'Fowey', 'Frome', 'Goole', 'Grays', 'Hayle', 'Hedon', 'Hythe',
          'Leeds', 'Leigh', 'Lewes', 'Louth', 'Luton', 'March', 'Olney', 'Otley', 'Poole', 'Ripon', 'Rugby', 'Sandy',
          'Selby', 'Soham', 'Stone', 'Thame', 'Thong', 'Tring', 'Truro', 'Wells', 'Wigan', 'Bath', 'Bude', 'Bury',
          'Clun', 'Deal', 'Diss', 'Eton', 'Hull', 'Hyde', 'Leek', 'Looe', 'Lydd', 'Ryde', 'Sale', 'Ware', 'Yarm',
          'Yate', 'York', 'Ely', 'Eye', 'Rye', 'Wem']
